### ISSUE TITLE
项目构建完成后，运行npm run dev 页面报错

### ISSUE THREAD

**Issue by xiwadai** [hj624608494/vue-shopping-mall#2]
![image](https://user-images.githubusercontent.com/24467843/28753189-a6f08c66-7562-11e7-8c43-b3d5168717c2.png)

![image](https://user-images.githubusercontent.com/24467843/28753191-b324dff0-7562-11e7-99b4-ca7f25a26e3b.png)

**Comment by hj624608494** [comment]
嗯嗯 请求的接口不存在  可以看这个项目  php 语言  https://github.com/hj624608494/vue-shopping-mall-php
